github:
  prebuilds:
    pullRequestsFromForks: true
    addComment: true
    
image: public.ecr.aws/pahudnet/gitpod-workspace:latest
#   file: .gitpod.Dockerfile


vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.5:9Wg0Glx/TwD8ElFBg+FKcQ==
